---
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Sync dependencies from uv.lock
        run: uv sync --locked

      - name: Build site
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_DRIVE_ID: ${{ secrets.GOOGLE_DRIVE_ID }}
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: "gcp-sa-key.json"
        run: |
          echo "$GCP_SA_KEY_JSON" > $GOOGLE_APPLICATION_CREDENTIALS
          ./scripts/build.sh

      - name: Upload dist/ to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy
        uses: actions/deploy-pages@v4
